<h1>new</h1>
<div class="form-container">
        <a class="back" href="<?php echo Mage::getBaseUrl(); ?>ems/event_index/list">
            <i class="fa fa-arrow-left"></i> Back
        </a>
        <?php
        $event = $this->getEvent();
        ?>
        <form method="POST" action="<?php echo $this->getUrl('*/*/save'); ?>">
            <input type="hidden" name="event[event_id]" value="<?php echo $event->getEventId(); ?>">

            <div class="form-group">
                <label for="name">Title:</label>
                <input type="text" id="name" name="event[title]" 
                    value="<?php  echo $event->getTitle(); ?>">
            </div>

            <div class="form-group">
                <label for="description">Description:</label>
                <textarea id="description" name="event[description]"  required><?php  echo $event->getDescription(); ?></textarea>
            </div>

            <div class="form-group">
                <label for="date">date:</label>
                <input type="date" name="event[date]" value="<?php echo $event->getDate(); ?>">
            </div>

            <div class="form-group">
                <label for="name">Location:</label>
                <input type="text" id="name" class = "validate-name" name="event[location]" 
                    value="<?php echo $event->getLocation(); ?>">
            </div>

            <div class="form-group">
                <label for="capacity">Capacity:</label>
                <input type="number" id="capacity"  name="event[capacity]" 
                    value="<?php echo $event->getCapacity(); ?>">
            </div>

            <input type="hidden" name="event[created_by]" value="<?php echo $this->getAdminId(); ?>">
            <button type="submit">Submit</button>

</form>